### ISSUE TITLE
Question: How to upload the artifacts

### ISSUE THREAD

**Issue by dirien** [pulumiverse/pulumi-aquasec#13]
Hi @ringods,

Do you know, if I need to do anything on my side for getting the artifacts uploaded to the appropriate repositories of Pulumiverse (npm, Java, etc.)

**Comment by ringods** [comment]
I still need to configure credentials on your repo. Will ping you when done.

**Comment by ringods** [comment]
@dirien I have configured the credentials on your repo. Your workflows still need to read these secrets. See here for which names to use:

https://github.com/pulumiverse/pulumi-unifi/blob/main/.github/workflows/release.yml#L2-L12
